# 线上配置文件
# @author Reflux
server:
  port: 8101
  servlet:
    context-path: /admin/api
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.215.230:3306/Re_api?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ZZYJDDN
  application:
    name: ReApi-admin
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 122.51.215.230
    port: 6379
    timeout: 5000
    password: 123456
  cloud:
    nacos:
      server-addr: 122.51.215.230:8848
      discovery:
        cluster-name: CS # 集群名称
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
dubbo:
  application: #应用名
    name: dubbo-springboot-demo-provider
    qosEnable: true
    qosPort: 22222
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://122.51.215.230:8848
#配置API-client的网关
reflux:
  gateway:
    host: http://localhost:8090

