server:
  port: 8123
  servlet:
    context-path: /interface
spring:
  application:
    name: interface-manager
  cloud:
    nacos:
      server-addr: 122.51.215.230:8848
      discovery:
        cluster-name: CS # 集群名称
#other-interface: ## 给其他接口微服务配置负载均衡规则，暂时无第三方接口
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则，优先本地集群
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数


