server:
  port: 8123
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      server-addr: 47.98.111.114:8848
      discovery:
        cluster-name: CS # 集群名称
